/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Certifications: typeof import('./src/components/Certifications.vue')['default']
    CheckBoxInput: typeof import('./src/components/CheckBoxInput.vue')['default']
    ContactInfo: typeof import('./src/components/ContactInfo.vue')['default']
    Enumeration: typeof import('./src/components/Enumeration.vue')['default']
    IBxsBriefcase: typeof import('~icons/bxs/briefcase')['default']
    IFluentWindowDevTools24Regular: typeof import('~icons/fluent/window-dev-tools24-regular')['default']
    IGameIconsGraduateCap: typeof import('~icons/game-icons/graduate-cap')['default']
    IHeroiconsUserCircle16Solid: typeof import('~icons/heroicons/user-circle16-solid')['default']
    ILineMdMoonTwotoneLoop: typeof import('~icons/line-md/moon-twotone-loop')['default']
    ILineMdSunnyLoop: typeof import('~icons/line-md/sunny-loop')['default']
    IMdiLocation: typeof import('~icons/mdi/location')['default']
    IMdiRemoveBold: typeof import('~icons/mdi/remove-bold')['default']
    IMiEmail: typeof import('~icons/mi/email')['default']
    IMynauiCodeHexagonSolid: typeof import('~icons/mynaui/code-hexagon-solid')['default']
    ISolarLinkBroken: typeof import('~icons/solar/link-broken')['default']
    ITokenScroll: typeof import('~icons/token/scroll')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RadioGroupInput: typeof import('./src/components/RadioGroupInput.vue')['default']
    Resume: typeof import('./src/components/Resume.vue')['default']
    ResumeLeft: typeof import('./src/components/ResumeLeft.vue')['default']
    ResumeRight: typeof import('./src/components/ResumeRight.vue')['default']
    SkillBar: typeof import('./src/components/SkillBar.vue')['default']
    ThemeSelector: typeof import('./src/components/ThemeSelector.vue')['default']
  }
}
